### ISSUE TITLE
Module dependency issue on miscreant-go

### ISSUE THREAD

**Issue by cosmosjane** [ovh/symmecrypt#21]
Hi, 

I was trying to test this module using the example that you have provided under README but can't make it work due to this error:

```
go: github.com/miscreant/miscreant-go@v0.0.0-20190903041724-6bebe170cbaf: parsing go.mod: unexpected module path "github.com/miscreant/miscreant.go"
go: error loading module requirements
```

I found that it may be due to renamed module and some parts of the code still referrencing to the old version of the module ( https://github.com/golang/go/wiki/Resolving-Problems-From-Modified-Module-Path )

I seems `github.com/miscreant/miscreant.go` was once `miscreant-go`.
I checked your repo and there still is a reference to the old module name under `\ciphers\aespmacsiv\aespmacsiv.go`

I'm still a bit new to all of these but from what I understand from link provided is that the lib should be updated. I apologize in advance if I am just missing something out.

**Comment by loopfz** [comment]
You're absolutely right, thank you for creating this issue!
It's not the first time the miscreant repo gets renamed.
See #12
I fixed it in #22 , hopefully this doesn't happen again.
If it does, we may have to reconsider keeping it as a built-in cipher.

**Comment by sneko** [comment]
Hi @loopfz , while trying to force "0.4.1" I get `go: github.com/ovh/symmecrypt@v0.4.1: unknown revision v0.4.1 ` even if the new release is on GitHub.

Do you know what's could be the cause? Thanks

**Comment by loopfz** [comment]
@sneko the 0.4.1 release tag doesn't follow the same format as the previous ones, it's a mistake.
"0.4.1" vs "v0.4.1". Use "0.4.1" instead and it should work.
v0.4.2 will be formatted correctly.
